Update

diff --git a/.github/workflows/tpu-tests.yml b/.github/workflows/tpu-tests.yml
--- a/.github/workflows/tpu-tests.yml
+++ b/.github/workflows/tpu-tests.yml
@@ -29,7 +29,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        pkg-name: ["fabric"]
+        pkg-name: ["fabric", "pytorch"]
     # 1 hour is the access token lifetime: https://cloud.google.com/docs/authentication/token-types#at-lifetime
     timeout-minutes: 60  # should match the timeout in the jsonnet files
 
@@ -87,22 +87,23 @@ jobs:
         cluster_name: ${{ env.GKE_CLUSTER }}
         location: ${{ env.GKE_ZONE }}
 
-    - name: Setup tmate session
-      uses: mxschmitt/action-tmate@v3
-
     - name: Deploy cluster
+      id: deploy
       run: |
         set -ue
         export PATH=$PATH:$HOME/go/bin
 
         job_name=$(jsonnet -J ml-testing-accelerators/ dockers/base-xla/tpu_workflow_${{ matrix.pkg-name }}.jsonnet | kubectl create -o name -f -)
         job_name=${job_name#job.batch/}
-        echo "Waiting for $job_name to launch..."
+        echo "Launched job name $job_name"
 
-        kubectl get pods  # information for debugging
+        pod_name=$(kubectl get pods --selector job-name=$job_name -o name)
+        pod_name=${pod_name#pod/}
+        echo "Pod name: $pod_name"
+        echo "pod_name=$pod_name" >> $GITHUB_OUTPUT
 
-        pod_name=$(kubectl wait --for condition=ready --timeout=30m pod -l job-name=$job_name -o name)
-        echo "GKE pod name: $pod_name"
+        echo "Waiting for the pod to be ready..."
+        kubectl wait --for condition=ready --timeout=30m pod $pod_name
 
         kubectl logs -f $pod_name --container=train > /tmp/full_output.txt
         if grep -q '<?xml version="1.0" ?>' /tmp/full_output.txt; then
@@ -115,9 +116,27 @@ jobs:
           cat /tmp/full_output.txt;
         fi
 
-        # cleanup
-        kubectl delete pod $job_name
+        failed=$(kubectl get job $job_name -o jsonpath={.status.failed})
+        if [ -z "$failed" ] || [ $failed -eq 1 ]; then
+          echo "Error: the job failed"
+          kubectl get job $job_name -o jsonpath={.status}
+          kubectl get pod $pod_name -o jsonpath={.status}
+          exit 1
+        fi
       shell: bash
+
+    - name: Cleanup
+      if: always
+      shell: bash
+      run: |
+        pod_name="${{ steps.deploy.outputs.pod_name }}"
+        echo "Running cleanup for $pod_name..."
+        # show all pods
+        kubectl get pods
+        # get events for the current pod
+        kubectl get event --field-selector involvedObject.name=$pod_name
+        # delete the pod
+        kubectl delete pod $pod_name
 
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v3
